version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu

environment:
  matrix:
    - ARCH: amd64
    - ARCH: arm32v6
    - ARCH: arm64v8
    - ARCH: i386
    - ARCH: ppc64le
    - ARCH: s390x

matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: i386
    - image: Visual Studio 2017
      ARCH: arm32v6
    - image: Visual Studio 2017
      ARCH: arm64v8
    - image: Visual Studio 2017
      ARCH: ppc64le
    - image: Visual Studio 2017
      ARCH: s390x

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

#deploy_script:
#  - ps: ./deploy.ps1
