version: 2

defaults: &defaults
  working_directory: ~/picapport
  machine: true

jobs:
  build_amd64:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for amd64
          command: make ARCHITECTURES=amd64
      - deploy:
          name: Push image for amd64 to dockerhub
          command: make ARCHITECTURES=amd64 push
  build_i386:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for i386
          command: make ARCHITECTURES=i386
      - deploy:
          name: Push image for i386 to dockerhub
          command: make ARCHITECTURES=i386 push
  build_arm32v6:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm32v6
          command: make ARCHITECTURES=arm32v6
      - deploy:
          name: Push image for arm32v6 to dockerhub
          command: make ARCHITECTURES=arm32v6 push
  build_arm64v8:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm64v8
          command: make ARCHITECTURES=arm64v8
      - deploy:
          name: Push image for arm64v8 to dockerhub
          command: make ARCHITECTURES=arm64v8 push
  build_ppc64le:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for ppc64le
          command: make ARCHITECTURES=ppc64le
      - deploy:
          name: Push image for ppc64le to dockerhub
          command: make ARCHITECTURES=ppc64le push
  build_s390x:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for s390x
          command: make ARCHITECTURES=s390x
      - deploy:
          name: Push image for s390x to dockerhub
          command: make ARCHITECTURES=s390x push
  manifest:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Generate multiarch manifest and push to dockerhub
          command: make manifest
  badge:
    <<: *defaults
    steps:
      - run:
          name: Call microbadger's webhook
          command: curl -X POST https://hooks.microbadger.com/images/whatever4711/picapport/h54qEvKKiyj8evp5FLbwRCouqks=

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_amd64:
          <<: *tag_filter
      - build_i386:
          <<: *tag_filter
      - build_arm32v6:
          <<: *tag_filter
      - build_arm64v8:
          <<: *tag_filter
      - build_ppc64le:
          <<: *tag_filter
      - build_s390x:
          <<: *tag_filter
      - manifest:
          requires:
            - build_amd64
            - build_i386
            - build_arm32v6
            - build_arm64v8
            - build_ppc64le
            - build_s390x
          <<: *tag_filter
      - badge:
         requires:
           - manifest
         <<: *tag_filter
